language: clojure
lein: lein2
before_script: ./bin/ci/before_script.sh
script: lein2 all test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
services:
  - rabbitmq
notifications:
  recipients:
    - michael@rabbitmq.com
